#!/usr/bin/env python3
"""Part 3: Hubs 183-253. Rebalanced toward rail, inland, ICD, border, trucking."""

import json

RAW3 = [
    (
        "CHOKE-CAPEGOOD",
        "Cape of Good Hope",
        ["Cape of Good Hope", "Cape Route"],
        "choke_point",
        ["sea"],
        -34.3568,
        18.4740,
        "South Africa",
        9,
        "Suez alternative routing around Africa",
    ),
    (
        "CHOKE-LOMBOK",
        "Lombok Strait",
        ["Lombok"],
        "choke_point",
        ["sea"],
        -8.4667,
        115.7667,
        "Indonesia",
        8,
        "Malacca alternative for deep-draft vessels",
    ),
    (
        "CHOKE-TAIWAN",
        "Taiwan Strait",
        ["Taiwan Strait"],
        "choke_point",
        ["sea"],
        24.0,
        119.0,
        "Taiwan",
        9,
        "Semiconductor supply chain corridor",
    ),
    (
        "CHOKE-CAPEHATT",
        "Cape Hatteras Shipping Lane",
        ["Cape Hatteras"],
        "choke_point",
        ["sea"],
        35.2271,
        -75.5353,
        "USA",
        7,
        "US East Coast shipping convergence zone",
    ),
    (
        "CHOKE-DARDANELLES",
        "Dardanelles Strait",
        ["Dardanelles"],
        "choke_point",
        ["sea"],
        40.1928,
        26.4108,
        "Turkey",
        8,
        "Turkish Straits southern gateway",
    ),
    (
        "RAIL-MEMPHIS",
        "Memphis Intermodal Yard",
        ["Memphis Rail"],
        "rail_hub",
        ["rail", "road"],
        35.1174,
        -89.9711,
        "USA",
        8,
        "Mississippi rail-barge interchange",
    ),
    (
        "RAIL-HOUSTON",
        "Houston Intermodal Terminal",
        ["Houston Rail"],
        "rail_hub",
        ["rail", "road"],
        29.712,
        -95.335,
        "USA",
        8,
        "Gulf Coast rail hub",
    ),
    (
        "RAIL-ATLANTA",
        "Atlanta Norfolk Southern Hub",
        ["Atlanta Rail"],
        "rail_hub",
        ["rail", "road"],
        33.78,
        -84.45,
        "USA",
        7,
        "Southeast US intermodal gateway",
    ),
    (
        "RAIL-SEATTLE",
        "Seattle BNSF Terminal",
        ["Seattle Rail"],
        "rail_hub",
        ["rail", "road"],
        47.55,
        -122.33,
        "USA",
        7,
        "PNW rail-port connector",
    ),
    (
        "RAIL-SAVANNAH",
        "Savannah Inland Port Mason",
        ["Mason Mega Rail"],
        "rail_hub",
        ["rail", "road"],
        32.08,
        -81.1,
        "USA",
        7,
        "Dual rail access mega terminal",
    ),
    (
        "RAIL-ANTWERP",
        "Antwerp Rail Terminal",
        ["Antwerp Rail"],
        "rail_hub",
        ["rail", "road"],
        51.31,
        4.38,
        "Belgium",
        7,
        "Belgian port hinterland connector",
    ),
    (
        "RAIL-LYON",
        "Lyon Rail Freight Hub",
        ["Lyon Rail"],
        "rail_hub",
        ["rail", "road"],
        45.7256,
        4.82,
        "France",
        7,
        "French rail crossroads",
    ),
    (
        "RAIL-MILAN",
        "Milano Smistamento Terminal",
        ["Milan Rail"],
        "rail_hub",
        ["rail", "road"],
        45.48,
        9.26,
        "Italy",
        7,
        "Northern Italy intermodal hub",
    ),
    (
        "RAIL-BANGALORE",
        "Whitefield ICD Bangalore",
        ["Bangalore Rail"],
        "rail_hub",
        ["rail", "road"],
        12.985,
        77.748,
        "India",
        7,
        "South India tech corridor ICD",
    ),
    (
        "RAIL-AHMEDABAD",
        "Ahmedabad ICD Khodiyar",
        ["Ahmedabad Rail"],
        "rail_hub",
        ["rail", "road"],
        23.01,
        72.585,
        "India",
        7,
        "Gujarat inland depot",
    ),
    (
        "RAIL-LUDHIANA",
        "Ludhiana ICD",
        ["Ludhiana Rail"],
        "rail_hub",
        ["rail", "road"],
        30.874,
        75.81,
        "India",
        7,
        "Punjab industrial ICD",
    ),
    (
        "RAIL-CHONGQING",
        "Chongqing Rail Port",
        ["Chongqing Rail"],
        "rail_hub",
        ["rail", "road"],
        29.563,
        106.551,
        "China",
        8,
        "Yangtze-BRI interchange",
    ),
    (
        "RAIL-YIWU",
        "Yiwu International Trade City",
        ["Yiwu"],
        "rail_hub",
        ["rail", "road"],
        29.3116,
        120.0861,
        "China",
        7,
        "China-Europe Express origin",
    ),
    (
        "RAIL-HARBIN",
        "Harbin Rail Terminal",
        ["Harbin"],
        "rail_hub",
        ["rail", "road"],
        45.8038,
        126.535,
        "China",
        7,
        "NE China-Russia rail gateway",
    ),
    (
        "RAIL-EKATERINBURG",
        "Ekaterinburg Rail Hub",
        ["Ekaterinburg"],
        "rail_hub",
        ["rail", "road"],
        56.8389,
        60.6057,
        "Russia",
        7,
        "Ural Mountains Trans-Siberian node",
    ),
    (
        "RAIL-KRASNOYARSK",
        "Krasnoyarsk Rail Terminal",
        ["Krasnoyarsk"],
        "rail_hub",
        ["rail", "road"],
        56.0184,
        92.8672,
        "Russia",
        6,
        "Central Siberian rail node",
    ),
    (
        "RAIL-ISTANBUL",
        "Halkali Rail Terminal",
        ["Istanbul Rail"],
        "rail_hub",
        ["rail", "road"],
        41.02,
        28.78,
        "Turkey",
        7,
        "Europe-Asia rail bridge terminus",
    ),
    (
        "RAIL-TEHRAN",
        "Tehran Rail Freight Terminal",
        ["Tehran Rail"],
        "rail_hub",
        ["rail", "road"],
        35.6892,
        51.389,
        "Iran",
        7,
        "Iranian rail crossroads",
    ),
    (
        "RAIL-LAHORE",
        "Lahore Dry Port",
        ["Lahore Rail"],
        "rail_hub",
        ["rail", "road"],
        31.5204,
        74.3587,
        "Pakistan",
        6,
        "Pakistan northern corridor",
    ),
    (
        "RAIL-NAIROBI",
        "Nairobi ICD Embakasi",
        ["Nairobi Rail"],
        "rail_hub",
        ["rail", "road"],
        -1.3,
        36.9,
        "Kenya",
        7,
        "SGR inland terminal",
    ),
    (
        "RAIL-JOBURG",
        "City Deep Container Terminal",
        ["Johannesburg Rail"],
        "rail_hub",
        ["rail", "road"],
        -26.22,
        28.08,
        "South Africa",
        7,
        "Southern Africa largest ICD",
    ),
    (
        "RAIL-SAOPAULO",
        "Santos-SP Rail Corridor",
        ["SP Rail"],
        "rail_hub",
        ["rail", "road"],
        -23.19,
        -46.88,
        "Brazil",
        7,
        "Brazil port-hinterland rail",
    ),
    (
        "RAIL-BUENOSAIRES",
        "Buenos Aires Rail Terminal",
        ["BA Rail"],
        "rail_hub",
        ["rail", "road"],
        -34.59,
        -58.37,
        "Argentina",
        6,
        "Argentine agriculture-port rail",
    ),
    (
        "ICD-JNPT",
        "JNPT-Dadri ICD Complex",
        ["Dadri ICD"],
        "distribution_hub",
        ["rail", "road"],
        28.58,
        77.55,
        "India",
        8,
        "India's largest ICD",
    ),
    (
        "ICD-KHORGOS",
        "Khorgos ICBC Dry Port",
        ["Khorgos Dry Port"],
        "distribution_hub",
        ["rail", "road"],
        44.23,
        80.26,
        "Kazakhstan",
        8,
        "China-Kazakhstan gauge-change dry port",
    ),
    (
        "ICD-ISTANBUL",
        "Istanbul Halkali Customs Hub",
        ["Halkali ICD"],
        "distribution_hub",
        ["rail", "road"],
        41.03,
        28.76,
        "Turkey",
        7,
        "Turkey primary customs terminal",
    ),
    (
        "ICD-RIYADH",
        "Riyadh Dry Port",
        ["Riyadh ICD"],
        "distribution_hub",
        ["rail", "road"],
        24.7136,
        46.6753,
        "Saudi Arabia",
        7,
        "Saudi interior customs hub",
    ),
    (
        "ICD-MELBOURNE",
        "Melbourne Intermodal Terminal",
        ["Somerton"],
        "distribution_hub",
        ["rail", "road"],
        -37.65,
        144.94,
        "Australia",
        7,
        "Victoria inland container interchange",
    ),
    (
        "BORDER-BUFFALONIAGARA",
        "Buffalo-Niagara Border Hub",
        ["Buffalo"],
        "distribution_hub",
        ["road", "rail"],
        42.9064,
        -78.8534,
        "USA",
        7,
        "US-Canada primary freight corridor",
    ),
    (
        "BORDER-ELPASOCD",
        "El Paso-Ciudad Juarez Gateway",
        ["El Paso"],
        "distribution_hub",
        ["road", "rail"],
        31.7619,
        -106.485,
        "USA",
        7,
        "Second busiest US-Mexico land port",
    ),
    (
        "BORDER-DETROIT",
        "Detroit-Windsor Tunnel Hub",
        ["Ambassador Bridge"],
        "distribution_hub",
        ["road", "rail"],
        42.31,
        -83.05,
        "USA",
        8,
        "US-Canada busiest auto trade crossing",
    ),
    (
        "BORDER-DOVER",
        "Port of Dover Freight",
        ["Dover Freight"],
        "distribution_hub",
        ["road", "sea"],
        51.1279,
        1.3134,
        "UK",
        7,
        "UK busiest ro-ro freight port",
    ),
    (
        "BORDER-BRENNER",
        "Brenner Pass Corridor",
        ["Brenner"],
        "distribution_hub",
        ["road", "rail"],
        47.0036,
        11.5078,
        "Austria",
        7,
        "Alpine Italy-Germany freight corridor",
    ),
    (
        "BORDER-BETUWE",
        "Betuwe Route Corridor",
        ["Betuweroute"],
        "distribution_hub",
        ["rail", "road"],
        51.9,
        5.5,
        "Netherlands",
        7,
        "Dedicated Rotterdam-Germany freight rail",
    ),
    (
        "HUB-INDIANAPOLIS",
        "Indianapolis Crossroads Hub",
        ["Indianapolis"],
        "distribution_hub",
        ["road", "rail", "air"],
        39.7684,
        -86.1581,
        "USA",
        7,
        "US geographic center logistics hub",
    ),
    (
        "HUB-COLUMBUS",
        "Columbus Rickenbacker Hub",
        ["Columbus OH"],
        "distribution_hub",
        ["road", "rail", "air"],
        39.8138,
        -82.9272,
        "USA",
        7,
        "Central Ohio multimodal hub",
    ),
    (
        "HUB-ZARAGOZA",
        "PLAZA Zaragoza",
        ["Zaragoza"],
        "distribution_hub",
        ["road", "rail", "air"],
        41.6488,
        -0.8891,
        "Spain",
        7,
        "Europe's largest logistics park",
    ),
    (
        "HUB-MUMBAI",
        "Mumbai JNPT Logistics Park",
        ["Nhava Sheva LP"],
        "distribution_hub",
        ["road", "rail"],
        18.96,
        73.0,
        "India",
        7,
        "India's largest port-adjacent bonded cluster",
    ),
    (
        "HUB-CHENNAI",
        "Chennai Logistics Park",
        ["Oragadam"],
        "distribution_hub",
        ["road", "rail"],
        12.85,
        79.98,
        "India",
        7,
        "Tamil Nadu automotive logistics zone",
    ),
    (
        "PORT-HAIFA",
        "Port of Haifa",
        ["Haifa"],
        "port",
        ["sea", "road", "rail"],
        32.8192,
        34.9983,
        "Israel",
        7,
        "Eastern Med container hub",
    ),
    (
        "PORT-TRIESTE",
        "Port of Trieste",
        ["Trieste"],
        "port",
        ["sea", "road", "rail"],
        45.6495,
        13.7768,
        "Italy",
        7,
        "Adriatic deep-water with rail to Central Europe",
    ),
    (
        "PORT-PORTSAID",
        "Port Said East",
        ["Port Said"],
        "port",
        ["sea", "road"],
        31.2653,
        32.3019,
        "Egypt",
        8,
        "Suez Canal north transshipment hub",
    ),
    (
        "PORT-NOVOROSSIYSK",
        "Port of Novorossiysk",
        ["Novorossiysk"],
        "port",
        ["sea", "road", "rail"],
        44.71,
        37.79,
        "Russia",
        7,
        "Russia Black Sea primary port",
    ),
    (
        "PORT-BREMERHAVEN",
        "Port of Bremerhaven",
        ["Bremerhaven"],
        "port",
        ["sea", "road", "rail"],
        53.5396,
        8.5809,
        "Germany",
        8,
        "Europe fourth largest container port",
    ),
    (
        "PORT-BARCELONA",
        "Port of Barcelona",
        ["Barcelona"],
        "port",
        ["sea", "road", "rail"],
        41.3569,
        2.1686,
        "Spain",
        7,
        "Western Med container hub",
    ),
    (
        "PORT-GENOA",
        "Port of Genoa",
        ["Genoa"],
        "port",
        ["sea", "road", "rail"],
        44.4056,
        8.9463,
        "Italy",
        7,
        "Italy's largest port",
    ),
    (
        "PORT-ALGECIRAS",
        "Port of Algeciras",
        ["Algeciras"],
        "port",
        ["sea", "road"],
        36.1281,
        -5.4437,
        "Spain",
        8,
        "Gibraltar transshipment hub",
    ),
    (
        "AIR-GUANGZHOU",
        "Baiyun International Airport",
        ["CAN"],
        "airport",
        ["air", "road"],
        23.3924,
        113.2988,
        "China",
        8,
        "South China primary cargo airport",
    ),
    (
        "AIR-DALLAS",
        "Dallas/Fort Worth International",
        ["DFW"],
        "airport",
        ["air", "road"],
        32.8968,
        -97.038,
        "USA",
        8,
        "Central US air cargo hub",
    ),
    (
        "AIR-JFK",
        "John F. Kennedy International",
        ["JFK"],
        "airport",
        ["air", "road"],
        40.6413,
        -73.7781,
        "USA",
        8,
        "US East Coast primary international cargo",
    ),
    (
        "AIR-RIYADH",
        "King Khalid International",
        ["RUH"],
        "airport",
        ["air", "road"],
        24.9576,
        46.6988,
        "Saudi Arabia",
        7,
        "Saudi primary air cargo terminal",
    ),
    (
        "AIR-CHENGDU",
        "Chengdu Tianfu International",
        ["TFU"],
        "airport",
        ["air", "road"],
        30.3134,
        104.4412,
        "China",
        7,
        "Western China BRI air hub",
    ),
    (
        "AIR-ZHENGZHOU",
        "Zhengzhou Xinzheng Airport",
        ["CGO"],
        "airport",
        ["air", "road"],
        34.5197,
        113.8408,
        "China",
        7,
        "iPhone assembly air export hub",
    ),
    (
        "RAIL-XIAN",
        "Xi'an International Port",
        ["Xi'an Rail"],
        "rail_hub",
        ["rail", "road"],
        34.263,
        108.9424,
        "China",
        8,
        "BRI inland port",
    ),
    (
        "RAIL-URUMQI",
        "Urumqi Rail Terminal",
        ["Urumqi"],
        "rail_hub",
        ["rail", "road"],
        43.8256,
        87.6168,
        "China",
        7,
        "Western China rail gateway to Central Asia",
    ),
    (
        "RAIL-HAMBURG",
        "Hamburg Rail Hub",
        ["Hamburg Maschen"],
        "rail_hub",
        ["rail", "road"],
        53.4598,
        9.961,
        "Germany",
        8,
        "Europe largest rail marshalling yard",
    ),
    (
        "RAIL-LOSANGELES",
        "LA Intermodal Complex",
        ["LA Rail"],
        "rail_hub",
        ["rail", "road"],
        33.8091,
        -118.2449,
        "USA",
        8,
        "US West Coast largest rail-port intermodal",
    ),
    (
        "RAIL-CHENNAI",
        "Chennai ICD Complex",
        ["Chennai Rail"],
        "rail_hub",
        ["rail", "road"],
        13.1368,
        80.2908,
        "India",
        7,
        "South India primary ICD cluster",
    ),
    (
        "RAIL-MUNDRA",
        "Mundra Rail Corridor",
        ["Mundra Rail"],
        "rail_hub",
        ["rail", "road"],
        22.75,
        69.7,
        "India",
        7,
        "Dedicated freight corridor for Mundra",
    ),
    (
        "HUB-MEMPHIS",
        "Memphis Logistics Hub",
        ["Memphis Freight"],
        "distribution_hub",
        ["road", "rail", "air"],
        35.1495,
        -90.049,
        "USA",
        8,
        "FedEx SuperHub adjacent intermodal",
    ),
    (
        "HUB-LOUISVILLE",
        "Louisville Logistics Park",
        ["Louisville KY"],
        "distribution_hub",
        ["road", "rail", "air"],
        38.2527,
        -85.7585,
        "USA",
        7,
        "UPS Worldport adjacent distribution",
    ),
    (
        "HUB-ROTTERDAM",
        "Rotterdam Distripark",
        ["Distripark"],
        "distribution_hub",
        ["road", "rail", "sea"],
        51.95,
        4.03,
        "Netherlands",
        8,
        "Europe largest port-adjacent distribution zone",
    ),
    (
        "PORT-LAZAROCARDENAS",
        "Port of Lazaro Cardenas",
        ["Lazaro Cardenas"],
        "port",
        ["sea", "road", "rail"],
        17.9356,
        -102.182,
        "Mexico",
        7,
        "Mexico Pacific deep-water port",
    ),
    (
        "PORT-PARANAGUA",
        "Port of Paranagua",
        ["Paranagua"],
        "port",
        ["sea", "road", "rail"],
        -25.5161,
        -48.5225,
        "Brazil",
        7,
        "Brazil grain export port",
    ),
    (
        "HUB-MONTERREY",
        "Monterrey Industrial Hub",
        ["Monterrey"],
        "distribution_hub",
        ["road", "rail"],
        25.6866,
        -100.3161,
        "Mexico",
        7,
        "Mexico nearshoring corridor hub",
    ),
]


def build_hub(r):
    return {
        "id": r[0],
        "display_name": r[1],
        "aliases": r[2],
        "type": r[3],
        "modes": r[4],
        "lat": r[5],
        "lon": r[6],
        "country": r[7],
        "importance": r[8],
        "strategic_role": r[9],
    }


if __name__ == "__main__":
    with open("backend/data/canonical_hubs.json", "r") as f:
        existing = json.load(f)
    existing_ids = {h["id"] for h in existing}
    new = [build_hub(r) for r in RAW3 if r[0] not in existing_ids]
    merged = existing + new
    with open("backend/data/canonical_hubs.json", "w") as f:
        json.dump(merged, f, indent=2)
    print(f"Part 3: +{len(new)}. Total: {len(merged)}")
